server:
  port: 8083



spring:
  datasource:
    username: root
    password: ksy521...
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/episp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-enums-package: com.anlogy.epsip.pojo